### ISSUE TITLE
Balance between a package and a collective config

### ISSUE THREAD

**Issue by casouri** [manateelazycat/aweshell#15]
So I think for Aweshell there is a balance point between being a package and a config.

If I understand it correctly, the goal of Aweshell is to provide a basic Eshell experience that is as good as - if not better than - zsh and fish. So Aweshell will not include **all** the useful packages out there for Eshell.

That being said, I think we can still provide a "recommended config" to add to Aweshell, which includes other cool packages and some best practices. That should make newcomers from zsh and fish more comfortable and start working faster. Maybe it can be an org file with documentation and snippets together.

How do you think?

**Comment by casouri** [comment]
If you like the idea, I’ll work on a PR.

**Comment by manateelazycat** [comment]
@casouri I hope aweshell out of the box.

Why user choose aweshell if user still need re-search config after install it?

If user want customize, should base on eshell, and not aweshell.

**Comment by casouri** [comment]
Wait wait don't close this yet. What if the user likes all the features but one? Is there any way to disable that particular package/feature? Plus, if we include all packages we can find, their version is basically locked by Aweshell.

I agree with the out-of-the-box idea, what I'm discussing about is those "fancy" or "not essential" features.

**Comment by casouri** [comment]
That’s true.
