### ISSUE TITLE
Auto suggest fails for ls "

### ISSUE THREAD

**Issue by oneness** [manateelazycat/aweshell#27]
Hi,
Thanks for this awesome mode. Recently started using it and found it to fit my workflow pretty well. However, I encountered an issue where I get 
```
Company: An error occurred in auto-begin
Company: backend aweshell-autosuggest error "No catch for tag: pcompleted, t" with args (candidates ls ")
```
When I type 
```
ls "
```
Not sure if it is a bug or some config issue. Will triage it when I get a chance. 

Thanks,

**Comment by manateelazycat** [comment]
Fix by https://github.com/manateelazycat/aweshell/commit/32035695ceb3cd7564b40f7547f352ead66326e3
