### ISSUE TITLE
Provide an option to disable prompt face configs

### ISSUE THREAD

**Issue by casouri** [manateelazycat/aweshell#3]
There is no easy way to disable them outside `aweshell.el` right now.

If I change `:inherite` attribute of any epe faces, 
it will not take effect because you set `:foreground` in `aweshell.el`.

**Comment by manateelazycat** [comment]
i will remove face from source code

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/aweshell/commit/8000e82b1ae7cb89b370ba23a58db7b464ae0c3b has remove face settings code
