### ISSUE TITLE
impl aweshell-switch-buffer?

### ISSUE THREAD

**Issue by RCmerci** [manateelazycat/aweshell#32]
I personally wrote a function 'eshell-buffer-list' to list all eshell buffers, and preselect the buffer whose 'default-directory' closest to the current buffer. I found it useful for me. Do you think it is necessary to add this to aweshell? If so, I can implement it.

**Comment by manateelazycat** [comment]
aweshell-buffer-list has implemented, please check out the source code.

**Comment by RCmerci** [comment]
Sorry that my words are not precise. I have read the source code, 'aweshell-buffer-list' is a variable recording aweshell buffers.
The 'aweshell-buffer-list' that I said in this issue refers to an interactive command that lists aweshell buffers and selects one to switch to that buffer. Maybe it should be called 'aweshell-switch-buffer'.

![image](https://user-images.githubusercontent.com/5608710/56858013-7fbb9c00-69a6-11e9-8c8a-9506bf496a31.png)

**Comment by manateelazycat** [comment]
@RCmerci I see, feel free to write PR, thanks!

**Comment by RCmerci** [comment]
please review https://github.com/manateelazycat/aweshell/pull/33 , thanks

**Comment by manateelazycat** [comment]
Has merged, thanks for PR
