### ISSUE TITLE
容易误删除输入区域外的内容

### ISSUE THREAD

**Issue by Kinneyzhang** [manateelazycat/aweshell#36]
用aweshell一直有个痛点：删除的时候会不小心删掉输入区域以外的内容，这时会报错“args out of range”，请问可以解决吗？
我看eshell在删除内容超出范围时会显示“read-only”无法删除，当光标在输入区域外删除时会自动跳转到正确的输入位置。
我用过其他的eshell插件也没解决这个问题，反而原生的eshell支持的最好。是不是在实现上有什么困难。

我的理想的输入状态是：除了必要的输入状态，如vim，emacs，命令行等，在其他不应该输入的区域输入时显示为只读状态并自动跳转到下一条命令行输入区域。

**Comment by manateelazycat** [comment]
这个我有空的时候看一下吧，最近有点忙。

**Comment by manateelazycat** [comment]
eshell 只会保护 Shell prompt 的区域，其他命令输出的区域并不会保护。
目前我个人不觉得这个问题是一个很严重的问题，如果真的对这点很在意，可以用我写的另外一个终端模拟器插件 multi-term.el
