### ISSUE TITLE
Why include exec-path-from-shell.el in Aweshell git repo?

### ISSUE THREAD

**Issue by MatthewZMD** [manateelazycat/aweshell#41]
exec-path-from-shell is another standalone package that has its [github page](https://github.com/purcell/exec-path-from-shell). Why include exec-path-from-shell.el in Aweshell git repo?

The reason I am asking this is that I downloaded exec-path-from-shell from other places, now it is prompting me when I `M-x list-load-path-shadows`
```
 ~/.emacs.d/site-elisp/aweshell/exec-path-from-shell hides /home/matthewzmd/.emacs.d/elpa/exec-path-from-shell-20190426.2227/exec-path-from-shell

1 Emacs Lisp load-path shadowing was found
```

I don't think it's necessary to put a standalone package in Aweshell.

**Comment by manateelazycat** [comment]
因为 exec-path-from-shell 是每一个Mac用户都会遇到的问题，如果这个插件不内置，大多数用户启动 eshell/aweshell 都会遇到任何命令都找不到的问题，我想90%的用户一开始就会放弃，而不是去研究为什么。

这也是为什么要内置这个插件的原因

**Comment by casouri** [comment]
The author don’t use melpa and don’t plan to. So the dependency is packaged into aweshell.
