### ISSUE TITLE
Indent error under Haskell ghci

### ISSUE THREAD

**Issue by Ynjxsjmh** [manateelazycat/aweshell#49]
Everytime type a charactor under Haskell ghci, an indent will be inserted after that char.

![Video_2020-01-13_155654_edit](https://user-images.githubusercontent.com/40143136/72240096-093af900-361e-11ea-80c7-3ead0ab9982c.gif)

Emacs version: GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30

**Comment by manateelazycat** [comment]
目前调试的，和aweshell内置的aweshell-autosuggest有关系

**Comment by manateelazycat** [comment]
Last version has fixed.
