### ISSUE TITLE
本地使用的oh my fish, 在aweshell中一输入命令，反应慢且还报错

### ISSUE THREAD

**Issue by jadestrong** [manateelazycat/aweshell#5]
错误如图·：
<img width="1426" alt="qq20180815-160800 2x" src="https://user-images.githubusercontent.com/18475217/44138264-eb8aa23e-a0a5-11e8-896b-037cecb88e79.png">

**Comment by manateelazycat** [comment]
从报错看, 看起来是 fish 的问题, 而不是 aweshell 的问题
