### ISSUE TITLE
Random spaces inserted for certain eshell forms

### ISSUE THREAD

**Issue by TeaWolf** [manateelazycat/aweshell#53]
When writing certain literals I get this weird insertion of spaces.
```ls >>>  #<d	f	d	f	s	>```
should have been ```ls >>> #<dsdfs>```
I was having this problem with some interactive programs as well but this seems to have been resolved in a recent update. Any idea where this could be coming from?

**Comment by manateelazycat** [comment]
Same bug with this: https://github.com/manateelazycat/aweshell/commit/a05583b44fe4018cab25b8e30edb2c65c085b58d

**Comment by manateelazycat** [comment]
This bug cause by aweshell auto suggest that completion best suggestion like fish.

I can't make this feature compatible with all terminal program, if this bug bothering you, please upgrade newest version, and disable auto suggest with below config:

```elisp
(setq aweshell-auto-suggestion-p nil)
```

**Comment by TeaWolf** [comment]
Fixed it perfectly. Thanks!
