### ISSUE TITLE
HIghlight bug

### ISSUE THREAD

**Issue by f4nyc** [manateelazycat/aweshell#60]
![aweshell-valid](https://user-images.githubusercontent.com/17718104/87145786-733a0f80-c2dc-11ea-8a83-014e2d00a777.gif)

**Comment by manateelazycat** [comment]
It's not a bug, it's a feature that point invalid command with red highlight.

**Comment by f4nyc** [comment]
If  i write `ls./` and insert space betwwen `ls` and `./`, then `./`part will be still red.  I don't think it's kinda feature.
