### ISSUE TITLE
Why not add this pakakge to the Mepla Emacs package repository?

### ISSUE THREAD

**Issue by hongyi-zhao** [manateelazycat/aweshell#63]
I noticed that this package is not available in [MELPA](https://melpa.org/#/). So, Why not add it to [the Mepla Emacs package repository](https://github.com/melpa/melpa)?

Regards,
HY

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/aweshell/issues/35#issuecomment-496742937
