### ISSUE TITLE
如何修改样式？终端能复用吗

### ISSUE THREAD

**Issue by nesteiner** [manateelazycat/aweshell#64]
![2021-06-28 20-10-31 的屏幕截图](https://user-images.githubusercontent.com/46296608/123634372-ef5e9780-d84c-11eb-8125-ccd994f71304.png)
  
个人喜欢简洁一点的样式，这个样式越看越不习惯，不知道有没有更改的方法，帖子里搜索关键词也没找到啊

**Comment by nesteiner** [comment]
另外我在考虑使用tmux，然后发现tmux在emacs上不是特别重要，我想问问有没有必要把emacs的shell改成可复用的

**Comment by manateelazycat** [comment]
不要加载 eshell-prompt-extras.el 即可。

**Comment by nesteiner** [comment]
不要加载？？ 代码动了一下就会产生一些错误，比如函数未定义  
看了一下 `eshell-prompt-extras.el`，发现那些样式都定义在 `epe-theme-pipeline` 函数中，我怕改坏掉

**Comment by manateelazycat** [comment]
> 不要加载？？ 代码动了一下就会产生一些错误，比如函数未定义
> 看了一下 `eshell-prompt-extras.el`，发现那些样式都定义在 `epe-theme-pipeline` 函数中，我怕改坏掉

努力学习吧，尝试自己改一下吧

**Comment by manateelazycat** [comment]
> 不要加载？？ 代码动了一下就会产生一些错误，比如函数未定义
> 看了一下 `eshell-prompt-extras.el`，发现那些样式都定义在 `epe-theme-pipeline` 函数中，我怕改坏掉

努力学习吧，尝试自己改一下吧
