### ISSUE TITLE
Shell command failed with code 1 and no output

### ISSUE THREAD

**Issue by kaiwk** [manateelazycat/aweshell#7]
When type in eshell, message like 'Shell command failed with code 1 and no output' would show in minibuffer very frequently. 

### Environment:
Mac OS X, Emacs 26.1 (brew install emacs)

**Comment by manateelazycat** [comment]
@kaiwk I push new patch : https://github.com/manateelazycat/aweshell/commit/b34b0084942fc2b68dca20491d0846f3b4768a73

Can you try it again ? 

Thanks

**Comment by manateelazycat** [comment]
@kaiwk Someone has confirm this patch fixed error.

Please re-open issue if you still have problem after use newest version

**Comment by kaiwk** [comment]
I checked usage of `history` in bash:
> history: usage: history [-c] [-d offset] [n] or history -awrn [filename] or history -ps arg [arg...]

Does it mean we should use it as `history -r ~/.bash_history`?

**Comment by kaiwk** [comment]
> When any of the `-w', `-r', `-a', or `-n' options are used, if filename is given, then it is used as the history file. If not, then the value of the HISTFILE variable is used. 

I have added `HISTFILE` to `exec-path-from-shell-variables`,  and now it gives `Shell command succeeded with no output`.
