### ISSUE TITLE
Update eshell-up and eshell-prompt-extras

### ISSUE THREAD

**Issue by GabrielFrigo4** [manateelazycat/aweshell#70]
The [eshell-up.el](https://github.com/peterwvj/eshell-up) and [eshell-prompt-extras.el](https://github.com/zwild/eshell-prompt-extras) codes are quite outdated compared to the "original" repositories

Is it possible to update these files in this repository?
If you want I can do it myself, but I would need a confirmation :)

**Comment by manateelazycat** [comment]
yes，sure

**Comment by GabrielFrigo4** [comment]
#71
