### ISSUE TITLE
Emacs hang after typing in eshell

### ISSUE THREAD

**Issue by kaiwk** [manateelazycat/aweshell#9]
Debug on quit gives:

>Debugger entered--Lisp error: (quit)
  looking-at("^[^#\nλ]* λ[#]* ")
  esh-autosuggest--prefix()
  esh-autosuggest(prefix)
  apply(esh-autosuggest prefix)
  company-call-backend-raw(prefix)
  apply(company-call-backend-raw prefix)
  company--force-sync(company-call-backend-raw (prefix) esh-autosuggest)
  company-call-backend(prefix)
  company--occurrence-predicate()
  #f(compiled-function (candidate) #<bytecode 0x4384cfc1>)("ll")
  cl-delete(nil ("ll") :if #f(compiled-function (candidate) #<bytecode 0x4384cfc1>))
  apply(cl-delete nil ("ll") :if #f(compiled-function (candidate) #<bytecode 0x4384cfc1>) nil)
  cl-delete-if(#f(compiled-function (candidate) #<bytecode 0x4384cfc1>) ("ll"))
  company-sort-by-occurrence(("ll"))
  company--transform-candidates(("ll"))
  company--postprocess-candidates(("ll"))
  company-calculate-candidates("ll")
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer Aweshell: ~/> #<window 3 on Aweshell: ~/> 21 598)
  apply(company-idle-begin (#<buffer Aweshell: ~/> #<window 3 on Aweshell: ~/> 21 598))
  timer-event-handler([t 23414 34947 42915 nil company-idle-begin (#<buffer Aweshell: ~/> #<window 3 on Aweshell: ~/> 21 598) nil 0])

I didn't change any default configuration.

### Environment
Max OS X, Emacs 26.1 (brew install emacs)

**Comment by manateelazycat** [comment]
@kaiwk Can you recur this bug with command "emacs -Q"

**Comment by kaiwk** [comment]
I start Emacs with `emacs -Q`, then evaluated the code below:

```
(add-to-list 'load-path (expand-file-name "~/path/to/aweshell/"))
(add-to-list 'load-path (expand-file-name "~/path/to/company/"))
(setenv "HISTFILE" "./.bash_history")
(require 'aweshell)
```
But the problem still exists from time to time, not frequently.  I find when prompt was modified, like `...λll` instead of `...λ ll` would be more likely to lead to this bug.

I may close this issue, as result of I can't reproduce it stably.
